export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  UNIQUE_CONSTRAINT: 'UNIQUE_CONSTRAINT',
  FOREIGN_KEY_CONSTRAINT: 'FOREIGN_KEY_CONSTRAINT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  PREDICTION_LOCKED: 'PREDICTION_LOCKED',
  GROUP_ACCESS_DENIED: 'GROUP_ACCESS_DENIED',
  SPORTSDB_NOT_CONFIGURED: 'SPORTSDB_NOT_CONFIGURED'
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
