// Códigos FIFA de 3 letras por nombre de país/selección, tal como los devuelve TheSportsDB (strHomeTeam/strAwayTeam).
export const COUNTRY_FIFA_CODES: Record<string, string> = {
  Afghanistan: 'AFG',
  Albania: 'ALB',
  Algeria: 'ALG',
  Andorra: 'AND',
  Angola: 'ANG',
  Argentina: 'ARG',
  Armenia: 'ARM',
  Australia: 'AUS',
  Austria: 'AUT',
  Azerbaijan: 'AZE',
  Bahrain: 'BHR',
  Bangladesh: 'BAN',
  Belarus: 'BLR',
  Belgium: 'BEL',
  Belize: 'BLZ',
  Benin: 'BEN',
  Bhutan: 'BHU',
  Bolivia: 'BOL',
  'Bosnia-Herzegovina': 'BIH',
  'Bosnia and Herzegovina': 'BIH',
  Botswana: 'BOT',
  Brazil: 'BRA',
  Bulgaria: 'BUL',
  'Burkina Faso': 'BFA',
  Burundi: 'BDI',
  Cambodia: 'CAM',
  Cameroon: 'CMR',
  Canada: 'CAN',
  'Cape Verde': 'CPV',
  'Central African Republic': 'CTA',
  Chad: 'CHA',
  Chile: 'CHI',
  China: 'CHN',
  Colombia: 'COL',
  Comoros: 'COM',
  Congo: 'CGO',
  'Costa Rica': 'CRC',
  Croatia: 'CRO',
  Cuba: 'CUB',
  Curacao: 'CUW',
  Cyprus: 'CYP',
  'Czech Republic': 'CZE',
  Czechia: 'CZE',
  Denmark: 'DEN',
  Djibouti: 'DJI',
  'Dominican Republic': 'DOM',
  Ecuador: 'ECU',
  Egypt: 'EGY',
  'El Salvador': 'SLV',
  England: 'ENG',
  'Equatorial Guinea': 'EQG',
  Eritrea: 'ERI',
  Estonia: 'EST',
  Eswatini: 'ESW',
  Ethiopia: 'ETH',
  Fiji: 'FIJ',
  Finland: 'FIN',
  France: 'FRA',
  Gabon: 'GAB',
  Gambia: 'GAM',
  Georgia: 'GEO',
  Germany: 'GER',
  Ghana: 'GHA',
  Greece: 'GRE',
  Guatemala: 'GUA',
  Guinea: 'GUI',
  'Guinea-Bissau': 'GNB',
  Haiti: 'HAI',
  Honduras: 'HON',
  Hungary: 'HUN',
  Iceland: 'ISL',
  India: 'IND',
  Indonesia: 'IDN',
  Iran: 'IRN',
  Iraq: 'IRQ',
  Ireland: 'IRL',
  'Republic of Ireland': 'IRL',
  Israel: 'ISR',
  Italy: 'ITA',
  'Ivory Coast': 'CIV',
  "Cote d'Ivoire": 'CIV',
  Jamaica: 'JAM',
  Japan: 'JPN',
  Jordan: 'JOR',
  Kazakhstan: 'KAZ',
  Kenya: 'KEN',
  Kosovo: 'KVX',
  Kuwait: 'KUW',
  Kyrgyzstan: 'KGZ',
  Laos: 'LAO',
  Latvia: 'LVA',
  Lebanon: 'LBN',
  Lesotho: 'LES',
  Liberia: 'LBR',
  Libya: 'LBY',
  Liechtenstein: 'LIE',
  Lithuania: 'LTU',
  Luxembourg: 'LUX',
  Madagascar: 'MAD',
  Malawi: 'MWI',
  Malaysia: 'MAS',
  Mali: 'MLI',
  Malta: 'MLT',
  Mauritania: 'MTN',
  Mauritius: 'MRI',
  Mexico: 'MEX',
  Moldova: 'MDA',
  Mongolia: 'MNG',
  Montenegro: 'MNE',
  Morocco: 'MAR',
  Mozambique: 'MOZ',
  Myanmar: 'MYA',
  Namibia: 'NAM',
  Nepal: 'NEP',
  Netherlands: 'NED',
  'New Zealand': 'NZL',
  Nicaragua: 'NCA',
  Niger: 'NIG',
  Nigeria: 'NGA',
  'North Korea': 'PRK',
  'North Macedonia': 'MKD',
  'Northern Ireland': 'NIR',
  Norway: 'NOR',
  Oman: 'OMA',
  Pakistan: 'PAK',
  Panama: 'PAN',
  'Papua New Guinea': 'PNG',
  Paraguay: 'PAR',
  Peru: 'PER',
  Philippines: 'PHI',
  Poland: 'POL',
  Portugal: 'POR',
  'Puerto Rico': 'PUR',
  Qatar: 'QAT',
  Romania: 'ROU',
  Russia: 'RUS',
  Rwanda: 'RWA',
  'San Marino': 'SMR',
  'Saudi Arabia': 'KSA',
  Scotland: 'SCO',
  Senegal: 'SEN',
  Serbia: 'SRB',
  'Sierra Leone': 'SLE',
  Singapore: 'SIN',
  Slovakia: 'SVK',
  Slovenia: 'SVN',
  Somalia: 'SOM',
  'South Africa': 'RSA',
  'South Korea': 'KOR',
  'Korea Republic': 'KOR',
  'South Sudan': 'SSD',
  Spain: 'ESP',
  'Sri Lanka': 'SRI',
  Sudan: 'SDN',
  Suriname: 'SUR',
  Sweden: 'SWE',
  Switzerland: 'SUI',
  Syria: 'SYR',
  Taiwan: 'TPE',
  'Chinese Taipei': 'TPE',
  Tajikistan: 'TJK',
  Tanzania: 'TAN',
  Thailand: 'THA',
  Togo: 'TOG',
  'Trinidad and Tobago': 'TRI',
  Tunisia: 'TUN',
  Turkey: 'TUR',
  Turkiye: 'TUR',
  Turkmenistan: 'TKM',
  Uganda: 'UGA',
  Ukraine: 'UKR',
  'United Arab Emirates': 'UAE',
  'United States': 'USA',
  USA: 'USA',
  Uruguay: 'URU',
  Uzbekistan: 'UZB',
  Vanuatu: 'VAN',
  Venezuela: 'VEN',
  Vietnam: 'VIE',
  Wales: 'WAL',
  Yemen: 'YEM',
  Zambia: 'ZAM',
  Zimbabwe: 'ZIM'
};

export function resolveFifaCode(countryName: string | null | undefined): string | null {
  if (!countryName) return null;
  const trimmed = countryName.trim();
  if (COUNTRY_FIFA_CODES[trimmed]) return COUNTRY_FIFA_CODES[trimmed];

  const normalized = Object.keys(COUNTRY_FIFA_CODES).find((key) => key.toLowerCase() === trimmed.toLowerCase());
  return normalized ? COUNTRY_FIFA_CODES[normalized] : null;
}
